version: '3.8'
services:
  dermsnap-db:
    image: postgres:14-alpine
    container_name: dermsnap-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dermsnap
    ports:
      - 5432:5432